In [ ]:
import numpy as np 
a = np.array([7,8,9])
print(a)

In [ ]:


import numpy as np
a = np.array([1,2,3,5,10])
b = np.array([0,4,5,2,7])
c = a + b
c[2]



In [96]:


import numpy as np
a = np.array([[1,2,3],[0,1,5]])
b = np.zeros([2,3], dtype=np.int16)
d = a + b + 1
print(d)



[[2 3 4]
 [1 2 6]]


In [97]:
len(a)

2

In [98]:


f = np.arange(10,25,4)
f



array([10, 14, 18, 22])

In [99]:


h2 = np.random.randint(5, size= 7)
h2.shape



(7,)

In [100]:
a.ndim

2

In [101]:


import numpy as np
a = np.array([[1,2,3],[0,1,5]])
b = np.array([[4,5,7],[2,9,1]])
g = a - b 
g



array([[-3, -3, -4],
       [-2, -8,  4]])

In [102]:
np.multiply(a,b)

array([[ 4, 10, 21],
       [ 0,  9,  5]])

In [103]:


np.sqrt(b).astype(int)



array([[2, 2, 2],
       [1, 3, 1]])

In [104]:


b.max(axis=0)



array([4, 9, 7])

In [105]:


b.sum(axis=1)



array([16, 12])

In [106]:


b[1,2]



1

In [107]:


a[0:1]



array([[1, 2, 3]])

In [108]:


b[0:2,2]



array([7, 1])

In [109]:


b[:1]



array([[4, 5, 7]])

In [110]:


b[b<6]



array([4, 5, 2, 1])

In [111]:


b.ravel()



array([4, 5, 7, 2, 9, 1])

In [112]:


b.reshape(3,2)



array([[4, 5],
       [7, 2],
       [9, 1]])

In [113]:


b.reshape(3,-1)



array([[4, 5],
       [7, 2],
       [9, 1]])

In [114]:


np.append(a,b)



array([1, 2, 3, 0, 1, 5, 4, 5, 7, 2, 9, 1])

In [115]:


np.append(a,b, axis=0)



array([[1, 2, 3],
       [0, 1, 5],
       [4, 5, 7],
       [2, 9, 1]])

In [116]:


np.append(a,b, axis=1)



array([[1, 2, 3, 4, 5, 7],
       [0, 1, 5, 2, 9, 1]])

In [117]:


np.insert(a, 1, 9)



array([1, 9, 2, 3, 0, 1, 5])

In [118]:


np.insert(a, 1, [5,6,7], axis=0)



array([[1, 2, 3],
       [5, 6, 7],
       [0, 1, 5]])

In [119]:


np.concatenate((a,b),axis=0)



array([[1, 2, 3],
       [0, 1, 5],
       [4, 5, 7],
       [2, 9, 1]])

In [120]:


np.vstack((a,b))



array([[1, 2, 3],
       [0, 1, 5],
       [4, 5, 7],
       [2, 9, 1]])

In [121]:


np.concatenate((a,b),axis=1)



array([[1, 2, 3, 4, 5, 7],
       [0, 1, 5, 2, 9, 1]])

In [122]:


np.hstack((a,b))



array([[1, 2, 3, 4, 5, 7],
       [0, 1, 5, 2, 9, 1]])

In [123]:


a = np.array([1,2,3])
b = np.arange(10,25,5)
np.c_[a,b]



array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])