# NumPy CheatSheet


__Introduction:__

Numpy (https://numpy.org/) is the fundamental package for scientific computing with Python. It contains among other things: a powerful N-dimensional array object, sophisticated (broadcasting) functions, useful linear algebra, Fourier transform, and random number capabilities.

__Common terms:__

In NumPy, each dimension is called an __axis__.

The number of axes is called the __rank__.

For example, the  3x4 matrix is an array of rank 2 (it is 2-dimensional).

The first axis has length 3, the second has length 4.

An array's list of axis lengths is called the __shape__ of the array.

For example, the above matrix's shape is (3, 4).

The rank is equal to the shape's length.

The __size__ of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)


In [8]:
import numpy as np

## Creating Array

In [11]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
print(a)
print ('-')
print(b)
print ('-')
print(c)

[1 2 3]
-
[[1.5 2.  3. ]
 [4.  5.  6. ]]
-
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [4]:
#This is an example cell

In [12]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [6]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [13]:
print(b)
print(c)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


## Initial Placeholders

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [18]:
d1 = np.arange(1,5) #Create an array of evenly spaced values (step value)
d = np.arange(10,25,3)

In [19]:
d1

array([1, 2, 3, 4])

In [20]:
d

array([10, 13, 16, 19, 22])

In [21]:
np.linspace(0,2,9) # Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
e = np.full((2,2),7) # Create a constant array

In [23]:
e

array([[7, 7],
       [7, 7]])

In [24]:
f = np.eye(2) #Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [25]:
np.random.random((2,2)) #Create an array with random values

array([[0.82670172, 0.3505752 ],
       [0.32417507, 0.93265809]])

In [29]:
np.random.randint(50)

29

In [30]:
randara = np.random.randint((50,20))
print(randara)

[37 13]


In [32]:
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

## Saving - Loading

In [ ]:
np.save('my_array', a) #adds .npy extension

In [ ]:
np.savez('array.npz', a, b)

In [ ]:
a1 = np.load('my_array.npy')
a1

In [ ]:
np.savetxt("myarray.txt", a, delimiter=" ")

In [ ]:
np.loadtxt("myarray.txt")

## Data Types

__np.int64__ Signed 64-bit integer types

__np.float32__ Standard double-precision floating point

__np.complex__ Complex numbers represented by 128 floats

__np.bool__ Boolean type storing TRUE and FALSE values

__np.object__ Python object type

__np.string___ Fixed-length string type

__np.unicode___ Fixed-length unicode type

## Inspecting

In [33]:
print(a.shape)
print(a)


(3,)
[1 2 3]


In [34]:
print(b.shape)
b

(2, 3)


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
len(a)


3

In [36]:
b.ndim

2

In [39]:
print(e)
e.size


[[7 7]
 [7 7]]


4

In [45]:
b.dtype

dtype('float64')

In [41]:
b.dtype.name

'float64'

In [42]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [43]:
bi = b.astype(int)

In [44]:
bi

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a

In [ ]:
bi

In [ ]:
b

## Array Mathematics

In [46]:
g = a - b

In [47]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [48]:
b - a

array([[0.5, 0. , 0. ],
       [3. , 3. , 3. ]])

In [ ]:
np.subtract(a,b)

In [49]:
a + b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
np.add(b,a)

In [ ]:
a / b

In [50]:
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [51]:
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
b

In [54]:
ar=np.array([1,2,3])
br=np.exp(ar) # calculates e^x for each x in your list where e is Euler's number (approximately 2.718)
br

array([ 2.71828183,  7.3890561 , 20.08553692])

In [55]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [56]:
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [57]:
ar

array([1, 2, 3])

In [58]:
np.sqrt(ar) 

array([1.        , 1.41421356, 1.73205081])

In [59]:
np.sin(a) 

array([0.84147098, 0.90929743, 0.14112001])

In [60]:
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [61]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [62]:
e

array([[7, 7],
       [7, 7]])

In [63]:
f

array([[1., 0.],
       [0., 1.]])

In [64]:
e.dot(f)

array([[7., 7.],
       [7., 7.]])

## Comparison

In [65]:
print(a)
print(b)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [91]:
a1 = np.array([1,2,3])
b1 = np.array([(1.5,2,3,5), (4,5,6,6), (7,8,9,10), (1,2,3,4)], dtype = float)
a1 == b1

/var/folders/v6/_tx89b9n2l51thmyq84j4tpm0000gp/T/ipykernel_87375/1766111065.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a1 == b1


False

In [92]:
a2 = np.array([1,2,3])
b2 = np.array([(1.5,2,3), (4,5,6), (7,8,9)], dtype = float)
a2 == b2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [93]:
a1 == b1

/var/folders/v6/_tx89b9n2l51thmyq84j4tpm0000gp/T/ipykernel_87375/3619879920.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a1 == b1


False

In [94]:
a == b

array([[False,  True,  True],
       [False, False, False]])

In [95]:
a < 2

array([ True, False, False])

## Aggregate Functions

In [96]:
a.sum()

6

In [97]:
a.min()

1

In [98]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [99]:
b.max()

6.0

In [100]:
b.shape

(2, 3)

In [101]:
b.max(axis=0)

array([4., 5., 6.])

In [102]:
b.sum()

21.5

In [103]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Copying Arrays

In [106]:
h = a.view()
h

array([1, 2, 3])

In [107]:
h.resize((2,6))

ValueError: cannot resize this array: it does not own its data

In [108]:
h = np.copy(a)
#difference copy vs view is that the copy creates a new array whereas the view is the view of the original array

In [109]:
h.resize((2,6))
h

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## Sorting Arrays

In [110]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [111]:
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [112]:
print(c.shape)
c

(2, 2, 3)


array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [ ]:
cs = c.sort(axis=0)

In [ ]:
cs

In [114]:
asort = np.array([[10, 11, 13, 22], [23, 7, 20, 14], [31, 11, 33, 17]])
print(asort)
np.sort(asort, axis= 1, kind=None, order=None) 

[[10 11 13 22]
 [23  7 20 14]
 [31 11 33 17]]


array([[10, 11, 13, 22],
       [ 7, 14, 20, 23],
       [11, 17, 31, 33]])

In [121]:
bsort = np.array([[[10, 11, 13, 22], [23, 7, 20, 14], [31, 11, 33, 17]], 
                     [[12, 11, 13, 23], [23, 7, 12, 14], [31, 34, 33, 17]], 
                     [[10, 6, 13, 22], [34, 7, 20, 14], [31, 34, 33, 7]]])

print(bsort)
print(np.sort(bsort, axis=2, kind=None, order=None))
print(np.sort(bsort, axis=1, kind=None, order=None))
print(np.sort(bsort, axis=0, kind=None, order=None))

[[[10 11 13 22]
  [23  7 20 14]
  [31 11 33 17]]

 [[12 11 13 23]
  [23  7 12 14]
  [31 34 33 17]]

 [[10  6 13 22]
  [34  7 20 14]
  [31 34 33  7]]]


array([[[10,  6, 13, 22],
        [23,  7, 12, 14],
        [31, 11, 33,  7]],

       [[10, 11, 13, 22],
        [23,  7, 20, 14],
        [31, 34, 33, 17]],

       [[12, 11, 13, 23],
        [34,  7, 20, 14],
        [31, 34, 33, 17]]])

## Subsetting, Slicing, Indexing

In [122]:
a

array([1, 2, 3])

In [123]:
a[2] #Select the element at the 2nd index

3

In [124]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [125]:
b[1,2] # Select the element at row 1 column 2 (equivalent to b[1][2])

6.0

In [126]:
a[0:2] # Select items at index 0 and 1

array([1, 2])

In [132]:
b[0:2,2] # Select items at rows 0 and 1 in column 1

array([3., 6.])

In [130]:
b[1,0:2] # Select items at rows 0 and 1 in column 1

array([4., 5.])

In [82]:
b[:1] # Select all items at row 0 (equivalent to b[0:1, :])

array([[1.5, 2. , 3. ]])

In [133]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [134]:
c.shape

(2, 2, 3)

In [140]:
c[0,:,:]

array([[1.5, 2. , 1. ],
       [4. , 5. , 6. ]])

In [139]:
c[0,...] #Same as [0,:,:]

array([[1.5, 2. , 1. ],
       [4. , 5. , 6. ]])

In [141]:
c[1:]

array([[[3., 2., 3.],
        [4., 5., 6.]]])

In [88]:
print(a)

[1 2 3]


In [89]:
a>1.5

array([False,  True,  True])

In [90]:
a[a>1.5] # Select elements from greater than 1.5

array([2, 3])

In [142]:
a

array([1, 2, 3])

In [143]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [149]:
b[1]

array([4., 5., 6.])

In [155]:
b[[1,1]]

array([[4., 5., 6.],
       [4., 5., 6.]])

In [156]:
b[[1,1],[0,0]]

array([4., 4.])

In [157]:
b[[1,1],[2,2]]

array([6., 6.])

In [158]:
b[[1,1],[3,3]]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [151]:
b[[1,0,1]]

array([[4. , 5. , 6. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [159]:
b[[1, 0, 1, 0]]

array([[4. , 5. , 6. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [1.5, 2. , 3. ]])

In [152]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [160]:
b[[1, 0, 1, 0]]

array([[4. , 5. , 6. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [1.5, 2. , 3. ]])

In [161]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## Array Manipulation

In [162]:
i = np.transpose(b)
print(i)
i.T

[[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [163]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [164]:
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [165]:
g.shape

(2, 3)

In [166]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [167]:
g.reshape(3,2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [168]:
h

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [169]:
z = h.resize((2,6))
print(z)
z

None


In [170]:
h

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [171]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [172]:
np.append(h,g)

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [173]:
a

array([1, 2, 3])

In [174]:
np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [175]:
a

array([1, 2, 3])

In [176]:
np.delete(a,1)

array([1, 3])

In [177]:
d

array([10, 13, 16, 19, 22])

In [178]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 13, 16, 19, 22])

In [179]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 13, 16, 19, 22])

In [180]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [181]:
np.vstack((a,b)) #Stack arrays vertically (row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [182]:
e

array([[7, 7],
       [7, 7]])

In [183]:
f

array([[1., 0.],
       [0., 1.]])

In [184]:
np.hstack((e,f)) #Stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [185]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [186]:
b2 = 2 * b
np.concatenate((b,b2),axis=1)

array([[ 1.5,  2. ,  3. ,  3. ,  4. ,  6. ],
       [ 4. ,  5. ,  6. ,  8. , 10. , 12. ]])

In [187]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [188]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [189]:
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]

## Examples

In [190]:
np.random.randint(5)

2

In [191]:
np.random.randint(5, size = 7)

array([1, 0, 0, 4, 1, 3, 2])

In [192]:
np.random.randint(2, 5, size = (3,2))

array([[3, 3],
       [4, 4],
       [3, 3]])

In [193]:
np.random.random(8)

array([0.00321274, 0.89008476, 0.79165354, 0.27414845, 0.68062812,
       0.48724022, 0.97632879, 0.23175355])

In [194]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [195]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [196]:
a = np.random.randint(5, size = (3,4))
a

array([[4, 1, 2, 1],
       [4, 3, 2, 0],
       [4, 4, 3, 3]])

In [197]:
a.ravel()

array([4, 1, 2, 1, 4, 3, 2, 0, 4, 4, 3, 3])

In [198]:
a.shape

(3, 4)

In [199]:
a

array([[4, 1, 2, 1],
       [4, 3, 2, 0],
       [4, 4, 3, 3]])

In [200]:
a.reshape(4,3)

array([[4, 1, 2],
       [1, 4, 3],
       [2, 0, 4],
       [4, 3, 3]])